name: Build extractors & package native JARs

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-extractors:
    strategy:
      matrix:
        os: [ macos-latest, windows-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.x
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      # --- build the PDF extractor ---
      - id: build-extractor
        name: Build extractor (Unix)
        if: runner.os != 'Windows'
        shell: bash
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install pdfplumber pyinstaller
          pyinstaller --onefile python/extract.py --name extract
          echo "artifact=extract" >> $GITHUB_OUTPUT

      - name: Build extractor (Windows)
        if: runner.os == 'Windows'
        id: build-extractor
        shell: pwsh
        run: |
          python -m venv venv
          .\venv\Scripts\Activate.ps1
          pip install pdfplumber pyinstaller
          pyinstaller --onefile python/extract.py --name extract.exe
          echo "artifact=extract.exe" >> $GITHUB_OUTPUT

      - name: Upload extractor
        uses: actions/upload-artifact@v4
        with:
          name: extractor-${{ matrix.os == 'Windows' && 'windows' || 'macos' }}
          path: dist/${{ steps.build-extractor.outputs.artifact }}

      # --- build the Excel translator ---
      - id: build-translator
        name: Build translator (Unix)
        if: runner.os != 'Windows'
        shell: bash
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install pandas openpyxl torch transformers sentencepiece pyinstaller
          pyinstaller --onefile python/translate_excel.py --name translate_excel
          echo "artifact=translate_excel" >> $GITHUB_OUTPUT

      - name: Build translator (Windows)
        if: runner.os == 'Windows'
        id: build-translator
        shell: pwsh
        run: |
          python -m venv venv
          .\venv\Scripts\Activate.ps1
          pip install pandas openpyxl torch transformers sentencepiece pyinstaller
          pyinstaller --onefile python/translate_excel.py --name translate_excel.exe
          echo "artifact=translate_excel.exe" >> $GITHUB_OUTPUT

      - name: Upload translator
        uses: actions/upload-artifact@v4
        with:
          name: translator-${{ matrix.os == 'Windows' && 'windows' || 'macos' }}
          path: dist/${{ steps.build-translator.outputs.artifact }}

  package:
    needs: build-extractors
    strategy:
      matrix:
        os: [ macos-latest, windows-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3

      # --- download the extractor into resources ---
      - name: Download Windows extractor
        if: runner.os == 'Windows'
        uses: actions/download-artifact@v4
        with:
          name: extractor-windows
          path: src/main/resources/native/windows

      - name: Download macOS extractor
        if: runner.os != 'Windows'
        uses: actions/download-artifact@v4
        with:
          name: extractor-macos
          path: src/main/resources/native/macos

      # --- download the translator into resources ---
      - name: Download Windows translator
        if: runner.os == 'Windows'
        uses: actions/download-artifact@v4
        with:
          name: translator-windows
          path: src/main/resources/native/windows

      - name: Download macOS translator
        if: runner.os != 'Windows'
        uses: actions/download-artifact@v4
        with:
          name: translator-macos
          path: src/main/resources/native/macos

      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '17'

      - name: Build & package JavaFX app
        run: mvn clean package -DskipTests

      - name: Upload installer artifacts
        uses: actions/upload-artifact@v4
        with:
          name: import-declaration-reader-plexus-tnt-${{ matrix.os == 'Windows' && 'windows' || 'macos' }}
          path: target/jpackage/**
