name: Build translator & package native JARs

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-translator:
    strategy:
      matrix:
        os: [ macos-latest, windows-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.x
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      # macOS/Linux build
      - id: build-translator-macos
        if: runner.os != 'Windows'
        name: Build translator (macOS/Linux)
        shell: bash
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install pandas openpyxl torch transformers sentencepiece pyinstaller
          pyinstaller --onefile python/translate_excel.py --name translate_excel
          echo "artifact=translate_excel" >> $GITHUB_OUTPUT

      # Windows build
      - id: build-translator-windows
        if: runner.os == 'Windows'
        name: Build translator (Windows)
        shell: pwsh
        run: |
          python -m venv venv
          .\venv\Scripts\Activate.ps1
          pip install pandas openpyxl torch transformers sentencepiece pyinstaller
          pyinstaller --onefile python/translate_excel.py --name translate_excel.exe
          echo "artifact=translate_excel.exe" >> $GITHUB_OUTPUT

      # upload
      - name: Upload translator (macOS)
        if: runner.os != 'Windows'
        uses: actions/upload-artifact@v4
        with:
          name: translator-macos
          path: dist/${{ steps.build-translator-macos.outputs.artifact }}

      - name: Upload translator (Windows)
        if: runner.os == 'Windows'
        uses: actions/upload-artifact@v4
        with:
          name: translator-windows
          path: dist/${{ steps.build-translator-windows.outputs.artifact }}

  package:
    needs: build-translator
    strategy:
      matrix:
        os: [ macos-latest, windows-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3

      # download exactly our translator binary
      - name: Download translator (macOS)
        if: runner.os != 'Windows'
        uses: actions/download-artifact@v4
        with:
          name: translator-macos
          path: src/main/resources/native/macos

      - name: Download translator (Windows)
        if: runner.os == 'Windows'
        uses: actions/download-artifact@v4
        with:
          name: translator-windows
          path: src/main/resources/native/windows

      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '17'

      - name: Build & package JavaFX app
        run: mvn clean package -DskipTests

      - name: Upload installer artifacts
        uses: actions/upload-artifact@v4
        with:
          name: translator-app-${{ matrix.os == 'Windows' && 'windows' || 'macos' }}
          path: target/jpackage/**
